name=TFG_Jaime_Perez
version=1.3.0
author=Jaime Perez
maintainer=Jaime Pérez <jaimeperezz@gmail.com>
sentence=Librería para el proyecto TFG de Jaime Perez.
paragraph= Librería desarrollada para mi TFG. En ella, he ido trabajando para lograr una coordinación de un sistema ferroviario utilizando medidas via UWB
category=Other
url=https://github.com/jimmyperezp/TFG_UWB
architectures=*